# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
cache: packages
warnings_are_errors: true
env:
  global:
    - NOT_CRAN=false
before_install:
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'covr::codecov()'
addons:
  apt:
    packages:
      - libapparmor-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - poppler-data
      - valgrind
